# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"

# Build documentation in the docs/ directory with mkdocs
mkdocs:
   configuration: mkdocs.yml

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf
